name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:

      - name: Say Hello
        run: echo "Hello ${{ inputs.name }}, I am a reusable workflow!"